# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJ9EUfUo-HWj4GwxXq8RGieqfPaJKkGk
"""

import feedparser
import datetime

feed = feedparser.parse("https://ajtwltsk.tistory.com/rss")

markdown_text = """
# I'm Super Junior! 🐱‍🏍
    > This is Minju-Kang's GitHub, who wants to be Super Junior.

<br>

<h1>Skills</h1>
<h3>Language</h3>
<div sytle="display:inline;">
<img alt="Python" src="https://img.shields.io/badge/Python-3776AB?style=flat-square&logo=Python&logoColor=white"/>
<img alt="Java" src="https://img.shields.io/badge/JAVA-007396?style=flat-square&logo=Java&logoColor=white"/>
<img alt="HTML5" src="https://img.shields.io/badge/HTML5-E34F26?style=flat-square&logo=HTML5&logoColor=white"/>
<img alt="CSS3" src="https://img.shields.io/badge/CSS3-1572B6?style=flat-square&logo=CSS3&logoColor=white"/>
<img alt="JavaScript" src="https://img.shields.io/badge/JavaScript-F7DF1E?style=flat-square&logo=JavaScript&logoColor=black"/>
</div>
<h3>IDE</h3>
<div sytle="display:inline;">
<img alt="Jupyter Notebook" src="https://img.shields.io/badge/Jupyter-F37626?style=flat-square&logo=Jupyter&logoColor=white"/>
<img alt="Visual Studio Code" src="https://img.shields.io/badge/Visual Studio Code-007ACC?style=flat-square&logo=Visual Studio Code&logoColor=white"/>
<img alt="Apache Tomcat" src="https://img.shields.io/badge/Apache Tomcat-F8DC75?style=flat-square&logo=Apache Tomcat&logoColor=black"/>
</div>
<br>

<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=minjukang727" >
<img src="https://github-readme-stats.vercel.app/api?username=MinjuKang727&show_icons=true&theme=radical">

<br><br>

"""

count = 0;
x = datetime.datetime.today()
today = datetime.datetime(x.year, x.month, x.day, 0, 0, 0, 0)
markdown_text2 = ""
for i in feed['entries']:
    markdown_text2 += f"- <a href=\"{i['link']}\"> {i['title']} </a><br>  \n"
    date = datetime.datetime.strptime(i['published'], "%a, %d %b %Y %H:%M:%S %z").replace(tzinfo=None)
    if (today - date).days + 1 <= 7 :
      count += 1

markdown_text += f"""
<br>

<img src="https://github.com/MinjuKang727/MinjuKang727/assets/108849480/0ac49170-7c8c-4c99-b0e5-86c414fc591c" alt="tistory-icon_IamSuperJunior" width="32px" align="left">

###  I'm Super Junior
    > I'm uploading contents on Tistory  (최근 일주일 간 게시글 `+ {count}`)  

{markdown_text2}
""" 
    
f = open("README.md", mode="w", encoding="utf-8")
f.write(markdown_text)
f.close()
