# This is a basic workflow to help you get started with Actions
name: Readme Update

  # Controls when the workflow will run
  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  # 1시간에 한번씩 아래 스크립트를 실행한다.
    schedule:
      - cron: "0 0 */1 * *"
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    # This workflow contains a single job called "build"
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
        - uses: actions/setup-python@v3
          with:
            python-version: '3.10'
# 라이브러리 추가작업
- name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser
      - name: Update README
        run: |
          python readme_update.py

      - name: Commit README
        run: |          
          git add .
          git config --local user.email "minjukang727@gmail.com"
          git config --local user.name "MinjuKang"
          git commit -m "Update README.md"
          git push origin +main
